app/models/user.py
from app.extensions import db

class User(db.Model):
    id = db.Column(db.String(150), primary_key=True)
    name = db.Column(db.String(150))
    email = db.Column(db.Text)

    def __repr__(self):
        return f'<User "{self.name}">'

app/__init__.py
from flask import *

from config import Config
from app.extensions import db


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    db.init_app(app)
    
    from app.user import bp as user_bp
    app.register_blueprint(user_bp)

    return app

app/user/__init__.py
from flask import Blueprint

bp = Blueprint('user', __name__)

from app.user import routes

app/user/routes.py
from flask import *
from app.user import bp
from app.extensions import db
from app.models.user import User
from app.utils.common_utils import *

@bp.route('/')
def index():
    users = User.query.all()
    return render_template('index.html', users=users)

@bp.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == "POST":
        name = request.form["name"]
        email = request.form["email"]
        user = User(id=generateId(), name=name, email=email)
        db.session.add(user)
        db.session.commit()
        flash("User has been added", "success")
        return redirect(url_for('user.index'))
    
    return render_template('create.html')

@bp.route('/delete/<user_id>')
def delete(user_id):
    user = db.session.query(User).filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    flash("User has been deleted", "success")
    return redirect(url_for('user.index'))

@bp.route('/edit/<user_id>', methods=['GET', 'POST'])
def edit(user_id):
    user = db.session.query(User).filter_by(id=user_id).first()
    if request.method == "POST":
        if user:
            user.name = request.form["name"]
            user.email = request.form["email"]
            db.session.commit()
            flash("User has been updated", "success")
        else:
            flash("Can't Update User", "error")
        return redirect(url_for('user.index'))
    
    return render_template('edit.html', user=user)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='image/favicon.svg') }}" type="image/x-icon">
    <script src="https://unpkg.com/feather-icons"></script>
    <title>FLASK CRUD APP</title>
</head>

<body>
    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.7.0.min.js"
        integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous">
    </script>
    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
</body>

</html>

app/templates/create.html
{% extends 'base.html' %}

{% block content %}
<section id="create-user">
    <div class="row vh-100">
        <div class="col-12 d-flex justify-content-center align-items-center">
            <div class="card w-75 p-3">
                <div class="card-header d-flex justify-content-between">
                    <h2 class="fw-bold text-secondary">Create User</h2>
                </div>
                <div class="card-body">
                    <form action="{{ url_for('user.create') }}" method="post">
                        <div class="mb-3">
                            <label for="name" class="form-label">Nama User</label>
                            <input type="text" class="form-control form-control-lg" id="name" name="name"
                                placeholder="Masukan Nama User">
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">Email User</label>
                            <input type="email" class="form-control form-control-lg" id="email" name="email"
                                placeholder="Masukan Email User">
                        </div>
                        <button type="submit" class="btn btn-primary d-flex align-items-center">
                            <i data-feather="save" height="20px" class="me-2"></i>Simpan User
                        </button>
                    </form>
                </div>
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                <div class="card-footer">
                    <ul class=flashes>
                        {% for category, message in messages %}
                        <li class="{{ category }}">{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
                {% endwith %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/edit.html
{% extends 'base.html' %}

{% block content %}
<section id="create-user">
    <div class="row vh-100">
        <div class="col-12 d-flex justify-content-center align-items-center">
            <div class="card w-75 p-3">
                <div class="card-header d-flex justify-content-between">
                    <h2 class="fw-bold text-secondary">Edit User</h2>
                </div>
                <div class="card-body">
                    <form action="{{ url_for('user.edit', user_id=user.id) }}" method="post">
                        <div class="mb-3">
                            <label for="name" class="form-label">Nama User</label>
                            <input type="text" class="form-control form-control-lg" id="name" name="name"
                                value="{{ user.name }}" placeholder="Masukan Nama User">
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">Email User</label>
                            <input type="email" class="form-control form-control-lg" id="email" name="email"
                                value="{{ user.email }}" placeholder="Masukan Email User">
                        </div>
                        <button type="submit" class="btn btn-primary d-flex align-items-center">
                            <i data-feather="save" height="20px" class="me-2"></i>Update User
                        </button>
                    </form>
                </div>
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                <div class="card-footer">
                    <ul class=flashes>
                        {% for category, message in messages %}
                        <li class="{{ category }}">{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
                {% endwith %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<section id="show-user">
    <div class="row vh-100">
        <div class="col-12 d-flex justify-content-center align-items-center">
            <div class="card w-75 p-3">
                <div class="card-header d-flex justify-content-between">
                    <h2 class="fw-bold text-secondary">Show User</h2>
                    <a href="{{ url_for('user.create') }}" role="button"
                        class="btn btn-primary d-flex align-items-center">
                        <i data-feather="user-plus" height="20px" class="me-2"></i>Tambah User
                    </a>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-hover table-bordered">
                        <thead class="bg-dark text-light">
                            <tr>
                                <th scope="col" class="text-center">No</th>
                                <th scope="col" class="text-center">Nama</th>
                                <th scope="col" class="text-center">Email</th>
                                <th scope="col" class="text-center">Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for user in users %}
                            <tr>
                                <th scope="row" width="8%" class="text-center align-middle">{{ loop.index }}</th>
                                <td class="align-middle">{{ user.name }}</td>
                                <td class="align-middle">{{ user.email }}</td>
                                <td width="15%" class="text-center align-middle">
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a href="{{ url_for('user.edit', user_id=user.id) }}" role="button"
                                            class="btn btn-primary">
                                            <i data-feather="edit"></i>
                                        </a>
                                        <a href="{{ url_for('user.delete', user_id=user.id) }}" role="button"
                                            class="btn btn-danger">
                                            <i data-feather="trash-2"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            <div class="card-footer">
                <ul class=flashes>
                    {% for category, message in messages %}
                    <li class="{{ category }}">{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
            {% endwith %}
        </div>
    </div>
</section>
{% endblock %}